#!/bin/sh

APP_DIR="/var/services/hackathon-api"
PYTHON_APP="app.py"
PID_DIR="$APP_DIR"
PID_FILE="$PID_DIR/app.pid"
LOG_DIR="$APP_DIR"
LOG_FILE="$LOG_DIR/app.log"
PYTHON_PATH=`which python3`

###############

# REDHAT chkconfig header

# chkconfig: - 58 74
# description: python-app is the script for starting a hackathon-api on boot.
### BEGIN INIT INFO
# Provides: python
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop python
# Description: Python process for app
### END INIT INFO

###############

USAGE="Usage: $0 {start|stop|restart|status} [--force]"
FORCE_OP=false

pid_file_exists() {
    [ -f "$PID_FILE" ]
}

get_pid() {
    echo "$(cat "$PID_FILE")"
}

is_running() {
    PID=$(get_pid)
    ! [ -z "$(ps aux | awk '{print $2}' | grep "^$PID$")" ]
}

start_it() {
    mkdir -p "$PID_DIR"
    mkdir -p "$LOG_DIR"

    echo "Starting hackathon-api ..."
    "$PYTHON_PATH" "$APP_DIR/$PYTHON_APP"  1>"$LOG_FILE" 2>&1 &
    echo $! > "$PID_FILE"
    echo "hackathon-api started with pid $!"
}

stop_process() {
    PID=$(get_pid)
    echo "Killing process $PID"
    kill -9 $PID
}

remove_pid_file() {
    echo "Removing pid file"
    rm -f "$PID_FILE"
}

start_app() {
    if pid_file_exists
    then
        if is_running
        then
            PID=$(get_pid)
            echo "hackathon-api already running with pid $PID"
            exit 1
        else
            echo "hackathon-api stopped, but pid file exists"
            echo "Forcing start anyways"
            remove_pid_file
            start_it
        fi
    else
        start_it
    fi
}

stop_app() {
    if pid_file_exists
    then
        if is_running
        then
            echo "Stopping hackathon-api ..."
            stop_process
            remove_pid_file
            echo "hackathon-api stopped"
        else
            echo "hackathon-api already stopped, but pid file exists"
            echo "Forcing stop anyways ..."
            remove_pid_file
            echo "hackathon-api stopped"
        fi
    else
        echo "hackathon-api already stopped, pid file does not exist"
        exit 1
    fi
}

status_app() {
    if pid_file_exists
    then
        if is_running
        then
            PID=$(get_pid)
            echo "hackathon-api running with pid $PID"
        else
            echo "hackathon-api stopped, but pid file exists"
        fi
    else
        echo "hackathon-api stopped"
    fi
}

case "$2" in
    --force)
        FORCE_OP=true
    ;;

    "")
    ;;

    *)
        echo $USAGE
        exit 1
    ;;
esac

case "$1" in
    start)
        start_app
    ;;

    stop)
        stop_app
    ;;

    restart)
        stop_app
        start_app
    ;;

    status)
        status_app
    ;;

    *)
        echo $USAGE
        exit 1
    ;;
esac
